# Logitech F10 Wireless Joystick
axis_linear: 1  # Forward/Back
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 2  # Left/Right
scale_angular: 0.4

enable_button: 4  # Trigger
enable_turbo_button: 5  # Button 2 aka thumb button
